name: Run Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Mostra i file presenti
        run: ls -la
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: node index.js

